spring:
  application:
    name: telegram-bot-klootviool
  data:
    mongodb:
      host: localhost
      port: 27017
      database: klootviool
      username: klootviool

bot:
  username: klootviool

imgur:
  url:
    base: https://api.imgur.com/3
    subreddit: ${imgur.url.base}/gallery/r

dankmemes:
  url: http://dankmemes.io/api/images/{subreddit}
